# Generated by Django 3.0.8 on 2020-08-15 21:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200806_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Pet.get_upload_path),
        ),
    ]
