# Generated by Django 3.0.8 on 2020-09-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pet_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rodent', 'Rodent'), ('Other', 'Other')], default='Dog', max_length=10),
        ),
    ]
