# Generated by Django 3.0.8 on 2020-09-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pet_name',
        ),
    ]
